### ISSUE TITLE
Error when importing LDR file

### ISSUE THREAD

**Issue by Bluebotlabz** [ScanMountGoat/ldr_tools_blender#21]
Using Blender 4.0, importing an ldraw file generated by Studio 2.0 with only a single EV3 remote in them, I get the following error

~~~python
  File "AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ldr_tools_blender\material.py", line 58, in get_material
    bsdf.inputs['Subsurface Color'].default_value = [r, g, b, 1.0]
KeyError: 'bpy_prop_collection[key]: key "Subsurface Color" not found'
~~~

**Comment by Bluebotlabz** [comment]
Just checked, this error only occurs in Blender 4.0 using the latest release

**Comment by ScanMountGoat** [comment]
This is already fixed on the latest commit but hasn't been released yet. The Blender 4.0 compatible release should be out in the next few days.
