### ISSUE TITLE
Misisng 1 required positional argument 'add_gap_between_parts' when importing ldr file

### ISSUE THREAD

**Issue by Bluebotlabz** [ScanMountGoat/ldr_tools_blender#22]
Latest addon version
Blender 4.0

~~~
Traceback (most recent call last):
  File "Blender Foundation\Blender\4.0\scripts\addons\ldr_tools_blender\operator.py", line 178, in execute
    import_ldraw(self, self.filepath, self.ldraw_path, ImportOperator.preferences.additional_paths,
TypeError: import_ldraw() missing 1 required positional argument: 'add_gap_between_parts'
~~~

**Comment by Bluebotlabz** [comment]
![Screenshot 2023-12-24 011616](https://github.com/ScanMountGoat/ldr_tools_blender/assets/69104218/d1bf2b69-e636-420b-9a51-9828fb5a435c)
I don't seem to get this option in the UI

**Comment by ScanMountGoat** [comment]
Are you uninstalling the addon and then installing from the [latest release](https://github.com/ScanMountGoat/ldr_tools_blender/releases/tag/0.3.0)? It looks like you may have files from two different versions of the addon somehow.

**Comment by Bluebotlabz** [comment]
Yeah I'm not sure how it happened
Fully reinstalling Blender and then installing the addon seems to work now though
