### ISSUE TITLE
Option to choose primatives/mesh/segment resolution - High(48) / Std(16) / Low(8)

### ISSUE THREAD

**Issue by philm400** [ScanMountGoat/ldr_tools_blender#24]
Higher resolution mesh data is available in the LDraw parts package than is currently used and applied by the add-on.

Suggest allowing an additional option at the import dialog to choose mesh resolution and utilise the additional 8 / 48 segmented parts data for users who want higher or lower resolution imports.

This would allow large/complex models to use a simpler lower 8-segment resolution for things like studs, saving valuable memory, file size and possibly reducing rendering times. Likewise, less complex models or where camera position is close in to the model and greater visual quality is required the 48-segment could be chosen at import.

**Comment by philm400** [comment]
I've played around with the 48-Seg folder with a copy of the LDraw parts folder by simply copying the 48 parts on top of the standard 16 parts and importing with the add-on does work bringing in the 48-seg studs etc.

Only issue I've found, which I think is to do with the add-on modifying the stud mesh data itself is a mesh based bevel being applied which is set to the standard 16-seg and introduced some gaps in alignment to the 48-seg stud top

Hopefully this is done programmatically in python or rust and can be easily updated based on user segment quality selection on import dialog

I'll upload some examples later on

**Comment by ScanMountGoat** [comment]
The primitive resolution is configurable in the `GeometrySettings` type in Rust. It just hasn't been added to Python or the addon import settings yet.

The addon doesn't add or remove geometry other than welding vertices by distance. The beveled edges use shader nodes. I'm not sure if every part in the parts library was built with different primitive resolutions in mind.
