### ISSUE TITLE
Traceback-Error when importing 

### ISSUE THREAD

**Issue by CptAmmogeddon** [ScanMountGoat/ldr_tools_blender#33]
![Bild_2024-08-07_165342981](https://github.com/user-attachments/assets/21646188-d22f-47e4-8a9c-eb355f24c18f)

I exported an LDraw-File using Brickling Studio, and after installing the LDraw-Library and the Blender-Addon, I get the pictured error-message when trying to import the file. What did I do wrong?

(Translation of the last error-message for non-german speakers: "The system cannot find the specified file."

**Comment by ScanMountGoat** [comment]
If you have studio installed, you can use its parts library. This should be detected automatically unless you have it installed in a non standard location. Is the library path correct in the importing menu?

**Comment by CptAmmogeddon** [comment]
It worked. Took a bit of trial-and-error, but I got it. Thank you for the quick help!
