### ISSUE TITLE
Parts in ldraw-File must be case-sensitive - Differences in cases leads to wrong import 

### ISSUE THREAD

**Issue by tobblx** [ScanMountGoat/ldr_tools_blender#34]
Hello,
I tried to Import a ldraw-File. The part-Names in the File are not the same case as the files in the parts-Folder.
If the upper-/lower-case does not match, the parts are not imported correctly as one mesh.

The part-File in the directory has the name:
"3842a.dat"

These are two lines in the ldraw-File:
1  15 136 -79 27 1 0 0 0 1 0 0 0 1 3842A.DAT => Import not correct
...
1  4 81 -52 -167 1 0 0 0 1 0 0 0 1 3842a.dat  => correctly imported

Example:
![grafik](https://github.com/user-attachments/assets/b8d707e4-a74c-4bc3-b1bf-9c9e3aae141a)

See also blend-File, part-File and ldraw-File in Attachment:
[Case-Senstitive-Bug.zip](https://github.com/user-attachments/files/16668912/Case-Senstitive-Bug.zip)

**Comment by tobblx** [comment]
Hi ScanMountGoat,
thank you for the fix! Wow - that was very fast!
I'm looking forward to the release of the version 0.4.2 ;-)

**Comment by ScanMountGoat** [comment]
The release is already available. If you're on windows, you'll need to uninstall the addon first to make sure it updates cleanly. 
https://github.com/ScanMountGoat/ldr_tools_blender/releases/tag/0.4.2

**Comment by tobblx** [comment]
Yes, I tried it. it works. The ldraw-model can now be imported correctly - without the previously needed workaround of editing the ldraw-file and converting the parts to lower case.
 Thank you!
