### ISSUE TITLE
Define shader/geometry node graphs in a DSL?

### ISSUE THREAD

**Issue by The0x539** [ScanMountGoat/ldr_tools_blender#36]
So this is an idea I've had for a while, ever since I was working on code to import the Studio/Eyesight XML shader definitions into modern Blender. The XML is a struggle to read, and the hardcoded-Python approach is only a modest improvement.

I've experimented with a couple alternative formats for defining shader graphs in an easier-to-maintain way, including a Python "library"/"DSL" slightly inspired by [Chisel](https://www.chisel-lang.org/). Unfortunately, the usage of that one didn't end up as clean-looking as I had hoped, and it required some supporting Python code for each different node type.

My best attempt so far uses StrictYAML files describing each node, its properties, and its inputs. I wouldn't call it "verbose", but it's definitely more "sparse" than the ideal embedded-in-Python version I had imagined. Compared to the "status quo" Python definitions, though, I'd say it's a definite improvement.

In [this branch](https://github.com/The0x539/ldr_tools_blender/tree/node-dsl), I've added my implementation and ported all the nodes to it, with a couple minor graph refactors along the way. I was about to make a draft PR before I noticed the contributing guidelines.

**Pros:**
- This way of defining shaders is subjectively *much* easier to author and maintain than any predecessor.
- Less Python code. The `node_dsl` module is introduced, but a sizable chunk of it is just defining the schema and corresponding static type information. Furthermore, adding new kinds of materials should require very little new Python code.
- The "shader language" is less expressive than doing it in Python (rule of least power).

**Cons:**
- Pulls in an external depdendency (`strictyaml`)
- Slightly slower (probably doesn't matter much, especially given that it's a one-time cost, not proportional to model)
- The "shader language" is less expressive than doing it in Python (a small amount of Python must remain for per-material 'customizations').
- The specific approach I've chosen includes nodes for speckled color and slope normals in all materials, simply disabling them by default and re-enabling when appropriate.
    - One possible way to address this would be to change the main shader tree to another node group that gets customized via some inputs, leaving only an extremely simple node graph at the top level of each material.

**Comment by ScanMountGoat** [comment]
I agree that the shader node code is a little gross. My preference would be to still do shader nodes in Python unless you think improving the existing approach isn't feasible. This allows for dealing with Blender changes in one place and doesn't require extra dependencies.

I've seen projects just commit a blend file to git, but binary files are difficult to manage with source control.

There are already some existing definition languages like MaterialX. I'm not sure how much cleaner this is than the existing code like you mentioned. https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/resources/Materials/Examples/StandardSurface/standard_surface_chess_set.mtlx.

Another approach is to write the "nodes" in shader code like open shading language (OSL). I don't think it's worth losing compatibility with eevee though. It's also possible to define a language like OSL and convert to nodes. The parsing could be fairly involved.

**Comment by The0x539** [comment]
That's somewhat similar to my "Python DSL" draft, but the main problem with that is needing to write code to support every single type of node.
*However,* my initial prototype was constrained by the idea of needing everything to be statically typed. The YAML approach sort of already sacrifices that, which gives me an idea:
```py
noise = graph.node(ShaderNodeNoise, position=(100, 200), inputs={ "Scale": 0.5, "Distortion": mix_node["Value"] })```
While writing this message, I initially thought to use keyword arguments for both properties and inputs, but in addition to capitalized names making that kind of ugly, *spaces* in names outright break that idea.

**Comment by ScanMountGoat** [comment]
That could work. Strings for the node type would better match how Blender's Python API is set up compared to enums. The problem with using an enum is needing to keep it up to date with all of Blender's supported node types. A statically typed API would be neat but probably best suited to a separate project due to the large amount of code required.

```python
noise = graph.node("ShaderNodeTexNoise", position=(100, 200), inputs={ "Scale": 0.5, "Distortion": mix_node["Value"] })
```

There may be a better way to handle nodes that support multiple modes or data types. Instead of changing the inputs, the node just has inputs for each mode. I'm not sure if this can be done with string keys.
https://docs.blender.org/api/current/bpy.types.NodeSocket.html#bpy.types.NodeSocket

```python
mix_normals = nodes.new("ShaderNodeMix")
mix_normals.data_type = "VECTOR"
mix_normals.location = (-430, 330)
links.new(subtract_studs.outputs["Value"], mix_normals.inputs["Factor"])
links.new(normals.outputs["Normal"], mix_normals.inputs[4])
links.new(slope_normals.outputs["Normal"], mix_normals.inputs[5])
```

**Comment by The0x539** [comment]
> That could work. Strings for the node type would better match how Blender's Python API is set up compared to enums.

I'm not using an enum, that's an actual value of type `type` imported from `bpy.types`. Going from that to a string is as simple as `.__name__`, and forces you to choose an actual node name, which is something I've gotten wrong many times. I've even thought about proposing the addition of an overload to `bpy` itself along the lines of:

```py
N = TypeVar('N', bound=Node)
@overload
def new(type: type[N]) -> N: ...
```

> Instead of changing the inputs, the node just has inputs for each mode. I'm not sure if this can be done with string keys.

First, the integer keys are fixed as far as I know, and my module fully supports them.

Second, if you "configure" the node first, then its sockets' `enabled` attribute will be set based on whether they're "active", and string key lookups seem to [filter based on that status](https://projects.blender.org/blender/blender/src/commit/06b25fee0e256184712bee39175ffc211a861da9/source/blender/makesrna/intern/rna_nodetree.cc#L2189-L2231).

**Comment by The0x539** [comment]
I've ported all the shader nodes in a `node-dsl-py` branch. I think what I have looks pretty good and is pretty easy to work with. I'll port the geometry node soon.
