### ISSUE TITLE
Studio minifigure head 3626cpb1966 does not import correctly

### ISSUE THREAD

**Issue by GlaucoGloster** [ScanMountGoat/ldr_tools_blender#45]
the head of the male figure of the set 60283 is glitched in blender 4.2.2 with the 4.3 version of the addon

**Comment by ScanMountGoat** [comment]
This should be fixed now on version 4.4. https://github.com/ScanMountGoat/ldr_tools_blender/releases/tag/0.4.4

**Comment by GlaucoGloster** [comment]
you don't know how much thankful i am towards you both for responding and for the fixing!!!
i hope you a good life!!!
