### ISSUE TITLE
the head again

### ISSUE THREAD

**Issue by GlaucoGloster** [ScanMountGoat/ldr_tools_blender#46]
now the head appears but not the face

**Comment by ScanMountGoat** [comment]
Are you in material or rendered mode in the viewport? What file are you trying to import?

**Comment by GlaucoGloster** [comment]
> Are you in material or rendered mode in the viewport? What file are you trying to import?

i have only tried tryied with layout and modelling mode and the missing face was both when opening the file as an .ldr and .io

**Comment by GlaucoGloster** [comment]
i have only tried tryied with layout and modelling mode and the missing face was both when opening the file as an .ldr and .io

**Comment by ScanMountGoat** [comment]
Blender won't show textures unless you change the viewport shading mode to material or rendered.

**Comment by GlaucoGloster** [comment]
i would like to import the model as a garry's mod model.
do you think the face could be lost in the process?

**Comment by ScanMountGoat** [comment]
Those models use vertex color, which appears in the basic mode.

**Comment by GlaucoGloster** [comment]
> Those models use vertex color, which appears in the basic mode.

**Comment by GlaucoGloster** [comment]
how do i subdivide the single pieces from the main model in blender?
