### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by GlaucoGloster** [ScanMountGoat/ldr_tools_blender#47]

**Comment by ScanMountGoat** [comment]
Issues are just for feature requests or bug reports. If you need help using Blender, there are many tutorials and resources available online.

**Comment by GlaucoGloster** [comment]
In the next versions of the tool could you make the color palettes
importable in Photoshop and similars?

Il dom 13 ott 2024, 14:23 SMG ***@***.***> ha scritto:

**Comment by ScanMountGoat** [comment]
There are various Lego color palette images available online, so I won't be adding this functionality to ldr_tools_blender itself. Please open a new issue if you have additional feature requests or bug reports in the future.

**Comment by GlaucoGloster** [comment]
Makes senses to me

Il lun 21 ott 2024, 19:15 SMG ***@***.***> ha scritto:
